version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: gaia-mcp-go
    main: ./main.go
    binary: gaia-mcp-go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X gaia-mcp-go/version.Version={{.Version}}
      - -X gaia-mcp-go/version.GitCommit={{.Commit}}
      - -X gaia-mcp-go/version.BuildDate={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64 # Windows ARM64 is less common, remove if needed

archives:
  - id: default
    # Updated to use 'formats' (plural) instead of deprecated 'format'
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        # Updated format_overrides to use 'formats' instead of deprecated 'format'
        formats:
          - zip
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  # Replaced deprecated 'name_template' with 'version_template'
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      # Only exclude very specific patterns that add no value to end users
      - "^test.*:"
      - "^ci.*:"
      - "merge conflict"
      - "Merge pull request"
      - "Merge remote-tracking branch"
      - "Merge branch"
      - "go mod tidy"
      - "^WIP:"
      - "^wip:"

release:
  github:
    owner: SipherAGI # Replace with your GitHub username
    name: gaia-mcp-go # Replace with your repo name
  draft: false
  prerelease: auto
  name_template: "Release v{{ .Version }}"
